---
- name: configure grub
  hosts: epam
  gather_facts: true
  become: true
  
  tasks:

  - name: Change grub file
    lineinfile: 
      path: /etc/default/grub
      backup: yes
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0 biosdevname=0\2'

  - name: run mkconfig
    command: grub2-mkconfig
     
  
